version: "3"
services:
  build:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - "./packages:/app/packages"
      - "./newdist:/app/dist"
    command: node scripts/build && node scripts/test
  test:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - "./packages:/app/packages"
      - "./newdist:/app/dist"
    command: node scripts/test
  serve:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - "./packages:/app/packages"
      - "./newdist:/app/dist"
    command: node scripts/serve
  serve-dev:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - "./packages:/app/packages"
      - "./newdist:/app/dist"
    command: node scripts/serve-dev

